### ISSUE TITLE
ioc.make bug

### ISSUE THREAD

**Issue by enniel** [poppinss/adonis-fold#8]
`ioc.make` don't worked with classes without name and space after `class` (generated by babel or other).

don't worked:

```js
// app/Foo.js
module.exports = class{}
```

```js
// test.js
make('App/Foo')
```

worked correctly:

```js
// app/Foo.js
module.exports = class {
}
```

```js
// app/Bar.js
module.exports = class Bar {
}
```

```js
// test.js
make('App/Foo')
make('App/Bar')
```

I think bug into regular expression of function `isClass`:

```js
const isClass = (fn) => {
  return typeof (fn) === 'function' && /^class\s/.test(toString.call(fn))
}
```

**Comment by thetutlage** [comment]
Mind sharing a PR for same

**Comment by henopied** [comment]
It would seem that `/^class\s/` does not allow for `class{}` because its looking for a space. Perhaps this regex might be better `/^class(?:\s+.*)?\s*{[\s\S]*}$/`. The part after `{` is optional. I tested this regex on the examples given and it seems to be fine. This regex even works on odd cases like:
``` javascript
class
ಠ_ಠ 
{
}
```
``` javascript
class     ಠ_ಠ{}
```
However it doesn't allow:
``` javascript
classಠ_ಠ{}
```

**Comment by thetutlage** [comment]
Sorry for getting late on this.

Following are not valid Javascript syntax, so there is no need to optimise for them.

- `class {}`
- `classFoo {}`
- `classಠ_ಠ{}`

Also `class     ಠ_ಠ{}` is not a common way to write the class. So I am okay skipping this too
